package beans;
// Generated Aug 12, 2018 9:48:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bus generated by hbm2java
 */
public class Bus  implements java.io.Serializable {


     private Integer id;
     private String model;
     private String creator;
     private int capacity;
     private Set cityLines = new HashSet(0);
     private Set interCityLines = new HashSet(0);
     private Set busPictureses = new HashSet(0);

    public Bus() {
    }

	
    public Bus(String model, String creator, int capacity) {
        this.model = model;
        this.creator = creator;
        this.capacity = capacity;
    }
    public Bus(String model, String creator, int capacity, Set cityLines, Set interCityLines, Set busPictureses) {
       this.model = model;
       this.creator = creator;
       this.capacity = capacity;
       this.cityLines = cityLines;
       this.interCityLines = interCityLines;
       this.busPictureses = busPictureses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }
    public Set getCityLines() {
        return this.cityLines;
    }
    
    public void setCityLines(Set cityLines) {
        this.cityLines = cityLines;
    }
    public Set getInterCityLines() {
        return this.interCityLines;
    }
    
    public void setInterCityLines(Set interCityLines) {
        this.interCityLines = interCityLines;
    }
    public Set getBusPictureses() {
        return this.busPictureses;
    }
    
    public void setBusPictureses(Set busPictureses) {
        this.busPictureses = busPictureses;
    }




}


