package beans;
// Generated Aug 12, 2018 10:50:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bus generated by hbm2java
 */
@Entity
@Table(name="bus"
    ,catalog="piabus"
)
public class Bus  implements java.io.Serializable {


     private Integer id;
     private String model;
     private String creator;
     private int capacity;
     private Set<CityLine> cityLines = new HashSet<CityLine>(0);
     private Set<InterCityLine> interCityLines = new HashSet<InterCityLine>(0);
     private Set<BusPictures> busPictureses = new HashSet<BusPictures>(0);

    public Bus() {
    }

	
    public Bus(String model, String creator, int capacity) {
        this.model = model;
        this.creator = creator;
        this.capacity = capacity;
    }
    public Bus(String model, String creator, int capacity, Set<CityLine> cityLines, Set<InterCityLine> interCityLines, Set<BusPictures> busPictureses) {
       this.model = model;
       this.creator = creator;
       this.capacity = capacity;
       this.cityLines = cityLines;
       this.interCityLines = interCityLines;
       this.busPictureses = busPictureses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="model", nullable=false, length=50)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="creator", nullable=false, length=50)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    
    @Column(name="capacity", nullable=false)
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bus")
    public Set<CityLine> getCityLines() {
        return this.cityLines;
    }
    
    public void setCityLines(Set<CityLine> cityLines) {
        this.cityLines = cityLines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bus")
    public Set<InterCityLine> getInterCityLines() {
        return this.interCityLines;
    }
    
    public void setInterCityLines(Set<InterCityLine> interCityLines) {
        this.interCityLines = interCityLines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bus")
    public Set<BusPictures> getBusPictureses() {
        return this.busPictureses;
    }
    
    public void setBusPictureses(Set<BusPictures> busPictureses) {
        this.busPictureses = busPictureses;
    }




}


