package beans;
// Generated Aug 12, 2018 10:50:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BusCompanys generated by hbm2java
 */
@Entity
@Table(name="bus_companys"
    ,catalog="piabus"
)
public class BusCompanys  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String number;
     private String adrerss;
     private String logo;
     private Set<InterCityLine> interCityLines = new HashSet<InterCityLine>(0);

    public BusCompanys() {
    }

	
    public BusCompanys(String name, String number, String adrerss, String logo) {
        this.name = name;
        this.number = number;
        this.adrerss = adrerss;
        this.logo = logo;
    }
    public BusCompanys(String name, String number, String adrerss, String logo, Set<InterCityLine> interCityLines) {
       this.name = name;
       this.number = number;
       this.adrerss = adrerss;
       this.logo = logo;
       this.interCityLines = interCityLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="number", nullable=false, length=50)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }

    
    @Column(name="adrerss", nullable=false, length=50)
    public String getAdrerss() {
        return this.adrerss;
    }
    
    public void setAdrerss(String adrerss) {
        this.adrerss = adrerss;
    }

    
    @Column(name="logo", nullable=false)
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="busCompanys")
    public Set<InterCityLine> getInterCityLines() {
        return this.interCityLines;
    }
    
    public void setInterCityLines(Set<InterCityLine> interCityLines) {
        this.interCityLines = interCityLines;
    }




}


