package beans;
// Generated Aug 12, 2018 9:48:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * BusCompanys generated by hbm2java
 */
public class BusCompanys  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String number;
     private String adrerss;
     private String logo;
     private Set interCityLines = new HashSet(0);

    public BusCompanys() {
    }

	
    public BusCompanys(String name, String number, String adrerss, String logo) {
        this.name = name;
        this.number = number;
        this.adrerss = adrerss;
        this.logo = logo;
    }
    public BusCompanys(String name, String number, String adrerss, String logo, Set interCityLines) {
       this.name = name;
       this.number = number;
       this.adrerss = adrerss;
       this.logo = logo;
       this.interCityLines = interCityLines;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getAdrerss() {
        return this.adrerss;
    }
    
    public void setAdrerss(String adrerss) {
        this.adrerss = adrerss;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public Set getInterCityLines() {
        return this.interCityLines;
    }
    
    public void setInterCityLines(Set interCityLines) {
        this.interCityLines = interCityLines;
    }




}


