package beans;
// Generated Aug 12, 2018 9:48:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CityLine generated by hbm2java
 */
public class CityLine  implements java.io.Serializable {


     private Integer id;
     private Bus bus;
     private String firstStation;
     private String otherStations;
     private int lastStation;
     private String departureTimes;
     private Set monthlyCardses = new HashSet(0);

    public CityLine() {
    }

	
    public CityLine(Bus bus, String firstStation, String otherStations, int lastStation, String departureTimes) {
        this.bus = bus;
        this.firstStation = firstStation;
        this.otherStations = otherStations;
        this.lastStation = lastStation;
        this.departureTimes = departureTimes;
    }
    public CityLine(Bus bus, String firstStation, String otherStations, int lastStation, String departureTimes, Set monthlyCardses) {
       this.bus = bus;
       this.firstStation = firstStation;
       this.otherStations = otherStations;
       this.lastStation = lastStation;
       this.departureTimes = departureTimes;
       this.monthlyCardses = monthlyCardses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }
    public String getFirstStation() {
        return this.firstStation;
    }
    
    public void setFirstStation(String firstStation) {
        this.firstStation = firstStation;
    }
    public String getOtherStations() {
        return this.otherStations;
    }
    
    public void setOtherStations(String otherStations) {
        this.otherStations = otherStations;
    }
    public int getLastStation() {
        return this.lastStation;
    }
    
    public void setLastStation(int lastStation) {
        this.lastStation = lastStation;
    }
    public String getDepartureTimes() {
        return this.departureTimes;
    }
    
    public void setDepartureTimes(String departureTimes) {
        this.departureTimes = departureTimes;
    }
    public Set getMonthlyCardses() {
        return this.monthlyCardses;
    }
    
    public void setMonthlyCardses(Set monthlyCardses) {
        this.monthlyCardses = monthlyCardses;
    }




}


