package beans;
// Generated Aug 12, 2018 9:48:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver  implements java.io.Serializable {


     private Integer id;
     private String firstname;
     private String lastname;
     private Date dob;
     private Date startedDriving;
     private Set interCityLines = new HashSet(0);

    public Driver() {
    }

	
    public Driver(String firstname, String lastname, Date dob, Date startedDriving) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.dob = dob;
        this.startedDriving = startedDriving;
    }
    public Driver(String firstname, String lastname, Date dob, Date startedDriving, Set interCityLines) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.dob = dob;
       this.startedDriving = startedDriving;
       this.interCityLines = interCityLines;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getStartedDriving() {
        return this.startedDriving;
    }
    
    public void setStartedDriving(Date startedDriving) {
        this.startedDriving = startedDriving;
    }
    public Set getInterCityLines() {
        return this.interCityLines;
    }
    
    public void setInterCityLines(Set interCityLines) {
        this.interCityLines = interCityLines;
    }




}


