package beans;
// Generated Aug 12, 2018 9:48:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employment generated by hbm2java
 */
public class Employment  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int discount;
     private Set users = new HashSet(0);

    public Employment() {
    }

	
    public Employment(String name, int discount) {
        this.name = name;
        this.discount = discount;
    }
    public Employment(String name, int discount, Set users) {
       this.name = name;
       this.discount = discount;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(int discount) {
        this.discount = discount;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


