package beans;
// Generated Aug 12, 2018 10:50:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employment generated by hbm2java
 */
@Entity
@Table(name="employment"
    ,catalog="piabus"
)
public class Employment  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int discount;
     private Set<User> users = new HashSet<User>(0);

    public Employment() {
    }

	
    public Employment(String name, int discount) {
        this.name = name;
        this.discount = discount;
    }
    public Employment(String name, int discount, Set<User> users) {
       this.name = name;
       this.discount = discount;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="discount", nullable=false)
    public int getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(int discount) {
        this.discount = discount;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="employment")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


