package beans;
// Generated Aug 12, 2018 9:48:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InterCityLine generated by hbm2java
 */
public class InterCityLine  implements java.io.Serializable {


     private Integer id;
     private Bus bus;
     private BusCompanys busCompanys;
     private Driver driver;
     private Date departure;
     private String firstStation;
     private Date arrival;
     private String lastStation;
     private String otherStations;
     private boolean isActive;
     private Set reservationses = new HashSet(0);

    public InterCityLine() {
    }

	
    public InterCityLine(Bus bus, BusCompanys busCompanys, Driver driver, Date departure, String firstStation, Date arrival, boolean isActive) {
        this.bus = bus;
        this.busCompanys = busCompanys;
        this.driver = driver;
        this.departure = departure;
        this.firstStation = firstStation;
        this.arrival = arrival;
        this.isActive = isActive;
    }
    public InterCityLine(Bus bus, BusCompanys busCompanys, Driver driver, Date departure, String firstStation, Date arrival, String lastStation, String otherStations, boolean isActive, Set reservationses) {
       this.bus = bus;
       this.busCompanys = busCompanys;
       this.driver = driver;
       this.departure = departure;
       this.firstStation = firstStation;
       this.arrival = arrival;
       this.lastStation = lastStation;
       this.otherStations = otherStations;
       this.isActive = isActive;
       this.reservationses = reservationses;
    }

    public InterCityLine(String busko, String string, String string0, String beograd, String novi_Pazar, String beogradKragujevacKraljevoNovi_Pazar) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }
    public BusCompanys getBusCompanys() {
        return this.busCompanys;
    }
    
    public void setBusCompanys(BusCompanys busCompanys) {
        this.busCompanys = busCompanys;
    }
    public Driver getDriver() {
        return this.driver;
    }
    
    public void setDriver(Driver driver) {
        this.driver = driver;
    }
    public Date getDeparture() {
        return this.departure;
    }
    
    public void setDeparture(Date departure) {
        this.departure = departure;
    }
    public String getFirstStation() {
        return this.firstStation;
    }
    
    public void setFirstStation(String firstStation) {
        this.firstStation = firstStation;
    }
    public Date getArrival() {
        return this.arrival;
    }
    
    public void setArrival(Date arrival) {
        this.arrival = arrival;
    }
    public String getLastStation() {
        return this.lastStation;
    }
    
    public void setLastStation(String lastStation) {
        this.lastStation = lastStation;
    }
    public String getOtherStations() {
        return this.otherStations;
    }
    
    public void setOtherStations(String otherStations) {
        this.otherStations = otherStations;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public Set getReservationses() {
        return this.reservationses;
    }
    
    public void setReservationses(Set reservationses) {
        this.reservationses = reservationses;
    }




}


