package beans;
// Generated Aug 12, 2018 10:50:49 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MonthlyCards generated by hbm2java
 */
@Entity
@Table(name="monthly_cards"
    ,catalog="piabus"
)
public class MonthlyCards  implements java.io.Serializable {


     private Integer id;
     private CityLine cityLine;
     private User user;
     private Integer cardStatus;

    public MonthlyCards() {
    }

    public MonthlyCards(CityLine cityLine, User user) {
       this.cityLine = cityLine;
       this.user = user;
    }
    public MonthlyCards(CityLine cityLine, User user, Integer cardStatus) {
       this.cityLine = cityLine;
       this.user = user;
       this.cardStatus = cardStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="line_id", nullable=false)
    public CityLine getCityLine() {
        return this.cityLine;
    }
    
    public void setCityLine(CityLine cityLine) {
        this.cityLine = cityLine;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Column(name="card_status")
    public Integer getCardStatus() {
        return cardStatus;
    }

    public void setCardStatus(Integer cardStatus) {
        this.cardStatus = cardStatus;
    }




}


