package beans;
// Generated Aug 12, 2018 10:50:49 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reservations generated by hbm2java
 */
@Entity
@Table(name = "reservations",
         catalog = "piabus"
)
public class Reservations implements java.io.Serializable {

    private Integer id;
    private InterCityLine interCityLine;
    private User user;
    private int numberOfCards;
    private Integer status;

    public Reservations() {
    }

    public Reservations(InterCityLine interCityLine, User user, int numberOfCards) {
        this.interCityLine = interCityLine;
        this.user = user;
        this.numberOfCards = numberOfCards;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "line_id", nullable = false)
    public InterCityLine getInterCityLine() {
        return this.interCityLine;
    }

    public void setInterCityLine(InterCityLine interCityLine) {
        this.interCityLine = interCityLine;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "number_of_cards", nullable = false)
    public int getNumberOfCards() {
        return this.numberOfCards;
    }

    public void setNumberOfCards(int numberOfCards) {
        this.numberOfCards = numberOfCards;
    }

    @Column(name = "status")
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
