package beans;
// Generated Aug 12, 2018 9:48:06 PM by Hibernate Tools 4.3.1



/**
 * Reservations generated by hbm2java
 */
public class Reservations  implements java.io.Serializable {


     private Integer id;
     private InterCityLine interCityLine;
     private User user;
     private int numberOfCards;

    public Reservations() {
    }

    public Reservations(InterCityLine interCityLine, User user, int numberOfCards) {
       this.interCityLine = interCityLine;
       this.user = user;
       this.numberOfCards = numberOfCards;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public InterCityLine getInterCityLine() {
        return this.interCityLine;
    }
    
    public void setInterCityLine(InterCityLine interCityLine) {
        this.interCityLine = interCityLine;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getNumberOfCards() {
        return this.numberOfCards;
    }
    
    public void setNumberOfCards(int numberOfCards) {
        this.numberOfCards = numberOfCards;
    }




}


