package beans;
// Generated Aug 12, 2018 9:48:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private Employment employment;
     private String firstname;
     private String lastname;
     private String username;
     private String pass;
     private String adress;
     private Date dob;
     private String phone;
     private String email;
     private Set reservationses = new HashSet(0);
     private Set monthlyCardses = new HashSet(0);

    public User() {
    }

	
    public User(Employment employment, String firstname, String lastname, String username, String pass, String adress, String phone) {
        this.employment = employment;
        this.firstname = firstname;
        this.lastname = lastname;
        this.username = username;
        this.pass = pass;
        this.adress = adress;
        this.phone = phone;
    }
    public User(Employment employment, String firstname, String lastname, String username, String pass, String adress, Date dob, String phone, String email, Set reservationses, Set monthlyCardses) {
       this.employment = employment;
       this.firstname = firstname;
       this.lastname = lastname;
       this.username = username;
       this.pass = pass;
       this.adress = adress;
       this.dob = dob;
       this.phone = phone;
       this.email = email;
       this.reservationses = reservationses;
       this.monthlyCardses = monthlyCardses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employment getEmployment() {
        return this.employment;
    }
    
    public void setEmployment(Employment employment) {
        this.employment = employment;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getReservationses() {
        return this.reservationses;
    }
    
    public void setReservationses(Set reservationses) {
        this.reservationses = reservationses;
    }
    public Set getMonthlyCardses() {
        return this.monthlyCardses;
    }
    
    public void setMonthlyCardses(Set monthlyCardses) {
        this.monthlyCardses = monthlyCardses;
    }




}


